### ISSUE TITLE
Is it possible to override the credentials for a build?

### ISSUE THREAD

**Issue by asarkar** [etiennestuder/gradle-credentials-plugin#14]
We have a use case where a build dynamically needs to use a different set of credentials. Instead of storing all the possible credentials that can ever be used under separate keys, we would like to override the credentials for that particular build. Wondering if this is currently feasible, and if not, can you please consider this ticket as a feature request?

**Comment by grv87** [comment]
+1 for this.

I would like to see an example how to use this plugin in CI environment. Slaves are created on-the-fly from pre-baked images and have no built-in credentials. Credentials are stored in Jenkins master and should be passed to the build somehow.
In theory I could first run `addCredentials` task of the current build to save credentials into the storage.
And then use them as usual.
But build script requires credentials to work, so I can't use it until I set up credentials.
Setting up separate project just to save credentials is a giant overhead.

**Comment by etiennestuder** [comment]
In your CI environment, you can pass the credentials via Gradle project properties and in your Gradle build logic, you first check for the presence of these project properties. If present, use the project properties, otherwise fall back to the credentials provided via this plugin.

**Comment by etiennestuder** [comment]
@asarkar 

What do we need this plugin for? This plugin is meant to store your credentials in an encrypted manner on your file system and to use them in your build when needed. _Injecting_ credentials into the build at invocation time is the not what this plugin tries to solve. 

It seems I do not understand what exactly you are requesting and how you envision this to work from a user's perspective. `We would like to override the credentials for that particular build.` does not suffice.

**Comment by etiennestuder** [comment]
@grv87 What you could do is to leverage [adding credentials ad-hoc from within a build](https://github.com/etiennestuder/gradle-credentials-plugin/blob/master/README.md#add-credentials-ad-hoc-from-within-a-build). You could do this via init script on CI. How you get the credentials out of Jenkins is your choice, but once you have them available in the Gradle init script, you can then set them ad-hoc on the credentials container as described in the link I shared. You _could_ also do the same thing right in the actual build script rather than in an init script, but that would be too much CI specific logic in the actual build, IMO.

**Comment by etiennestuder** [comment]
Given the unclear nature of what the plugin should provide that it currently does not, and given there are options to override/set the credentials to be used in an ad-hoc, non-persistent way without changes to this plugin, I'm going to close this issue.
