### ISSUE TITLE
How to configure addCredentials with --no-scan

### ISSUE THREAD

**Issue by kamenskyen** [etiennestuder/gradle-credentials-plugin#37]
Hello, this is a feature request, how to configure a task with a parameter "--no-scan".
Because all passwords are sent to the console of the gradle enterprise in plain text.

**Comment by etiennestuder** [comment]
I would add some build logic to your Gradle build that turns off publishing of build scans when you find a task called `addCredentials` on the cmd line.

As an alternative or addition, rather than passing the credentials on the cmd line in plain text, read them from a file/environment when you invoke the `./gradlew addCredentials ...` bash command.

You might also find some inspiration in this article:
https://www.netmeister.org/blog/passing-passwords.html
